### ISSUE TITLE
Sample code is not working on pho-0.2.1 release

### ISSUE THREAD

**Issue by mcun0s** [eHarmony/pho#10]
I was trying to use the PHO, but I cannot't use this library because the API of sample code has been deprecated.
Where can I find new sample code?

The both of Phoenix official site and here has incorrect sample code.
Could you update the sample code for user?
Thanks for your help!

Best regards,
Unho.

**Comment by vvangapandu** [comment]
Let me update the sample code. are you looking for any specific repository methods?

**Comment by mcun0s** [comment]
@vvangapandu : First of all, thanks for looking to this issue.

I'm using Gradle from Maven central repository. But I can't find the library on that.
But it's not an issue because I can download it from download link.

Best regards,
Unho.

**Comment by vvangapandu** [comment]
Hi @mcun0s 
Fixed the build issue by removing our custom phoenix-hbase dependency (which we uploaded in our internal nexus-repository) and changing it to standard phoenix core library.

It pulls hortenworks dependencies from their nexus repository.
http://repo.hortonworks.com/nexus/content/groups/public/

We are still testing our internal project, but please feel free to try this and let us know if you find any issues.

After build, it also uploads pho library in below location if you are interested in just jar file.

https://oss.sonatype.org/service/local/repositories/releases/content/com/eharmony/pho/pho/0.2.1/pho-0.2.1.jar

**Comment by vvangapandu** [comment]
Closing the issue as fix has been provided.
