### ISSUE TITLE
build issue

### ISSUE THREAD

**Issue by moumita1981** [eHarmony/pho#9]
Could not find artifact org.apache.phoenix:phoenix:jar:4.4.0-HBase-1.1-client-minimal in Maven central 
Are you using Maven central or some other repository?

**Comment by vvangapandu** [comment]
This is not available in maven central repository, we are using Hortenworks distribution. i will try and upload this to nexus.

**Comment by MichaelHoppe** [comment]
Can you tell me where the nexus-repository is located?

**Comment by vvangapandu** [comment]
Hi MichaelHoppe, 
fixed the build issue by removing our custom phoenix-hbase dependency (which we uploaded in our internal nexus-repository) and changing it to standard phoenix core library.

It pulls hortenworks dependencies from their nexus repository.
http://repo.hortonworks.com/nexus/content/groups/public/

We are still testing our internal project, but please feel free to try this and let us know if you find any issues.

After build, it also uploads pho library in below location if you are interested in just jar file.

https://oss.sonatype.org/service/local/repositories/releases/content/com/eharmony/pho/pho/0.2.1/pho-0.2.1.jar

**Comment by vvangapandu** [comment]
Closing the issue, as fix has been provided.

**Comment by ewenkel** [comment]
This needs to be reopened as http://repo.hortonworks.com/nexus/content/groups/public/ no longer exists.
